### ISSUE TITLE
"gameOver" Method not implemented

### ISSUE THREAD

**Issue by scottcrossen** [scottcrossen/ConnectFour#1]
The front-end jquery has a method called gameOver that needs to call for the row in the table (session) to be deleted. I haven't made the back-end functionality though. In addition, the database should really clear itself every now and then.

**Comment by ghost** [comment]
Do you want me to just code an ajax call that goes to a url like /reset or something, which just reinitializes the board to nothing, and sets the player turn to the person who just lost? then when the client gets the response, javascript will just repaint the board to show nothing and the game can be played again

**Comment by scottcrossen** [comment]
the ajax call should use the http method: delete (not get or post) with a query/body referencing the session. As it is, the board will reset itself whenever someone hits the first player button in the modal. The issue is that we don't want the database filling up and so that method needs to be implemented. I'll write the route in express probably after thursday so we can use it for our next lab.

**Comment by scottcrossen** [comment]
fixed it. The app deleted sessions on lose() condition.
