### ISSUE TITLE
Modal Close

### ISSUE THREAD

**Issue by scottcrossen** [scottcrossen/ConnectFour#2]
When you click outside of the modal, the modal closes. A listener needs to be attached to reload the modal untill the fields are set.

**Comment by ghost** [comment]
i fixed the modal issue - you can't click anywhere or type anything to get out. also, if either the name or game id is left blank, an alert appears at the bottom of the modal saying they can't leave them blank

**Comment by scottcrossen** [comment]
great. I have the pertinent code on the back-end to also take care of the null-session case (the name has a default though).
